export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const FILTER_VIDEOGAME = "FILTER_VIDEOGAME";
export const GET_VIDEOGAME = "GET_VIDEOGAME";
export const UNVIDEOGAME = "UNVIDEOGAME";
export const UNFILTERVIDEOGAMES = "UNFILTERVIDEOGAMES";